import { Project, Task, TeamMember } from 'types/types';

export const initialProjects: Project[] = [
  {
    id: 'project-1',
    name: 'Project Alpha',
    description: 'Main product development',
    color: '#3b82f6',
  },
  {
    id: 'project-2',
    name: 'Project Beta',
    description: 'Marketing website redesign',
    color: '#10b981',
  },
  {
    id: 'project-3',
    name: 'Project Gamma',
    description: 'Mobile app development',
    color: '#f59e0b',
  },
];

export const initialTasks: Task[] = [
  // Project Alpha Tasks
  {
    id: 'task-1',
    title: 'Research competitors',
    description: 'Analyze top 5 competitors in the market',
    deadline: '2023-06-15',
    priority: 'high',
    status: 'todo',
    projectId: 'project-1',
    assignee: 'team-1',
    createdAt: '2023-05-01',
  },
  {
    id: 'task-2',
    title: 'Create wireframes',
    description: 'Design initial wireframes for the dashboard',
    deadline: '2023-06-20',
    priority: 'medium',
    status: 'todo',
    projectId: 'project-1',
    assignee: 'team-2',
    createdAt: '2023-05-02',
  },
  {
    id: 'task-3',
    title: 'User interviews',
    description: 'Conduct interviews with 10 potential users',
    deadline: '2023-06-25',
    priority: 'low',
    status: 'todo',
    projectId: 'project-1',
    assignee: 'team-3',
    createdAt: '2023-05-03',
  },
  {
    id: 'task-4',
    title: 'Setup development environment',
    description: 'Install and configure necessary tools',
    deadline: '2023-06-10',
    priority: 'medium',
    status: 'in-progress',
    projectId: 'project-1',
    assignee: 'team-4',
    createdAt: '2023-05-04',
  },
  {
    id: 'task-5',
    title: 'Create component library',
    description: 'Build reusable UI components',
    deadline: '2023-06-30',
    priority: 'high',
    status: 'in-progress',
    projectId: 'project-1',
    assignee: 'team-2',
    createdAt: '2023-05-05',
  },
  {
    id: 'task-6',
    title: 'Initial user testing',
    description: 'Get feedback on the first prototype',
    deadline: '2023-06-05',
    priority: 'medium',
    status: 'completed',
    projectId: 'project-1',
    assignee: 'team-3',
    createdAt: '2023-05-06',
  },
  {
    id: 'task-7',
    title: 'Stakeholder presentation',
    description: 'Present project progress to stakeholders',
    deadline: '2023-06-01',
    priority: 'high',
    status: 'completed',
    projectId: 'project-1',
    assignee: 'team-1',
    createdAt: '2023-05-07',
  },

  // Project Beta Tasks
  {
    id: 'task-8',
    title: 'Design homepage',
    description: 'Create new homepage design',
    deadline: '2023-07-10',
    priority: 'high',
    status: 'todo',
    projectId: 'project-2',
    assignee: 'team-2',
    createdAt: '2023-05-08',
  },
  {
    id: 'task-9',
    title: 'SEO optimization',
    description: 'Improve website SEO',
    deadline: '2023-07-15',
    priority: 'medium',
    status: 'in-progress',
    projectId: 'project-2',
    assignee: 'team-4',
    createdAt: '2023-05-09',
  },
  {
    id: 'task-10',
    title: 'Content strategy',
    description: 'Develop content strategy for the new website',
    deadline: '2023-07-20',
    priority: 'high',
    status: 'todo',
    projectId: 'project-2',
    assignee: 'team-1',
    createdAt: '2023-05-10',
  },
  {
    id: 'task-11',
    title: 'User testing',
    description: 'Conduct user testing for the new website design',
    deadline: '2023-07-25',
    priority: 'medium',
    status: 'todo',
    projectId: 'project-2',
    assignee: 'team-3',
    createdAt: '2023-05-11',
  },
  {
    id: 'task-12',
    title: 'Analytics setup',
    description: 'Set up analytics tracking for the website',
    deadline: '2023-07-30',
    priority: 'low',
    status: 'completed',
    projectId: 'project-2',
    assignee: 'team-4',
    createdAt: '2023-05-12',
  },

  // Project Gamma Tasks
  {
    id: 'task-13',
    title: 'Mobile app wireframes',
    description: 'Design wireframes for mobile app',
    deadline: '2023-07-20',
    priority: 'high',
    status: 'todo',
    projectId: 'project-3',
    assignee: 'team-2',
    createdAt: '2023-05-13',
  },
  {
    id: 'task-14',
    title: 'API design',
    description: 'Design API endpoints for the mobile app',
    deadline: '2023-07-25',
    priority: 'high',
    status: 'in-progress',
    projectId: 'project-3',
    assignee: 'team-4',
    createdAt: '2023-05-14',
  },
  {
    id: 'task-15',
    title: 'User authentication',
    description: 'Implement user authentication for the mobile app',
    deadline: '2023-07-30',
    priority: 'high',
    status: 'todo',
    projectId: 'project-3',
    assignee: 'team-4',
    createdAt: '2023-05-15',
  },
  {
    id: 'task-16',
    title: 'UI component library',
    description: 'Create UI component library for the mobile app',
    deadline: '2023-08-05',
    priority: 'medium',
    status: 'todo',
    projectId: 'project-3',
    assignee: 'team-2',
    createdAt: '2023-05-16',
  },
  {
    id: 'task-17',
    title: 'Push notifications',
    description: 'Implement push notifications for the mobile app',
    deadline: '2023-08-10',
    priority: 'medium',
    status: 'todo',
    projectId: 'project-3',
    assignee: 'team-3',
    createdAt: '2023-05-17',
  },
];

export const teamMembers: TeamMember[] = [
  {
    id: 'team-1',
    name: 'Alex Johnson',
    role: 'Project Manager',
    avatar: '/placeholder.svg?height=40&width=40',
    email: 'alex@example.com',
  },
  {
    id: 'team-2',
    name: 'Sam Taylor',
    role: 'UI/UX Designer',
    avatar: '/placeholder.svg?height=40&width=40',
    email: 'sam@example.com',
  },
  {
    id: 'team-3',
    name: 'Jordan Lee',
    role: 'Frontend Developer',
    avatar: '/placeholder.svg?height=40&width=40',
    email: 'jordan@example.com',
  },
  {
    id: 'team-4',
    name: 'Casey Morgan',
    role: 'Backend Developer',
    avatar: '/placeholder.svg?height=40&width=40',
    email: 'casey@example.com',
  },
];
